# Generated by Django 5.0.1 on 2024-02-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="thumbnail",
            field=models.ImageField(default=1, upload_to="thumbnails"),
            preserve_default=False,
        ),
    ]
